/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkShiftsImport } from './routes/work-shifts'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WorkShiftsRoute = WorkShiftsImport.update({
  id: '/work-shifts',
  path: '/work-shifts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/work-shifts': {
      id: '/work-shifts'
      path: '/work-shifts'
      fullPath: '/work-shifts'
      preLoaderRoute: typeof WorkShiftsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work-shifts': typeof WorkShiftsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work-shifts': typeof WorkShiftsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/work-shifts': typeof WorkShiftsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work-shifts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work-shifts'
  id: '__root__' | '/' | '/work-shifts'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkShiftsRoute: typeof WorkShiftsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkShiftsRoute: WorkShiftsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/work-shifts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/work-shifts": {
      "filePath": "work-shifts.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
